# Generated by Django 6.0.5 on 2026-05-22 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('opis', models.TextField()),
                ('detalji', models.TextField(blank=True, null=True)),
                ('slika', models.URLField()),
                ('trajanje', models.CharField(max_length=50)),
                ('cijena', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('polasci', models.CharField(max_length=50)),
                ('wifi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaxiRezervacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('broj_telefona', models.CharField(max_length=20)),
                ('lokacija_polaska', models.CharField(max_length=200)),
                ('lokacija_odredista', models.CharField(max_length=200)),
                ('vrijeme', models.DateTimeField()),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polaziste', models.CharField(max_length=100)),
                ('vrijeme_polaska', models.TimeField()),
                ('vrijeme_dolaska', models.TimeField()),
                ('cijena', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aktivna', models.BooleanField(default=True)),
                ('destinacija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linije', to='Aplikacija.destinacija')),
            ],
        ),
        migrations.CreateModel(
            name='Karta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_putnika', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('broj_telefona', models.CharField(max_length=20)),
                ('datum_putovanja', models.DateField()),
                ('broj_karata', models.PositiveIntegerField(default=1)),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('linija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplikacija.linija')),
            ],
        ),
    ]
