# Generated by Django 6.0.5 on 2026-05-08 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacija', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VozniRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrijeme_polaska', models.TimeField()),
                ('vrijeme_dolaska', models.TimeField()),
                ('linija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplikacija.linija')),
            ],
        ),
    ]
