# Generated by Django 6.0.5 on 2026-05-19 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacija', '0002_voznired'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('slika', models.URLField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxiRezervacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('broj_telefona', models.CharField(max_length=20)),
                ('lokacija_polaska', models.CharField(max_length=200)),
                ('lokacija_odredista', models.CharField(max_length=200)),
                ('vrijeme', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Karta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_putnika', models.CharField(max_length=100)),
                ('broj_telefona', models.CharField(max_length=20)),
                ('datum_putovanja', models.DateField()),
                ('broj_karata', models.IntegerField()),
                ('linija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplikacija.linija')),
            ],
        ),
    ]
