# Generated by Django 6.0.5 on 2026-05-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacija', '0003_destinacija_taxirezervacija_karta'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinacija',
            name='cijena',
            field=models.CharField(default='Nije uneseno', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinacija',
            name='detalji',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinacija',
            name='polasci',
            field=models.CharField(default='Nije uneseno', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinacija',
            name='trajanje',
            field=models.CharField(default='Nije uneseno', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinacija',
            name='wifi',
            field=models.CharField(default='Nije uneseno', max_length=50),
            preserve_default=False,
        ),
    ]
